### ISSUE TITLE
"Malformed module path" error when importing the package

### ISSUE THREAD

**Issue by SoftExpert** [y001j/UringNet#1]
Hello,

The following error is raised when running `go mod tidy` on a new project.
I tried to run one of the examples in the repository.

```go
go: testURing imports
        github.com/y001j/UringNet imports
        uring: malformed module path "uring": missing dot in first path element
```

Thanks exploring this interesting subject and best of luck!

Best regards,
SoftExpert

**Comment by y001j** [comment]
Thanks for reporting the issue, I have updated the mod file. I think it should work. If any problem, please reopen it.
